apiVersion: v1
kind: Pod
metadata:
  name: test-buildah
spec:
  containers:
  - name: buildah
    image: quay.io/buildah/stable:v1.14.3
    env:
    - name: STORAGE_DRIVER
      value: vfs
    command: ["/bin/sh"]
    args:
    - -c
    - |
      sed -i -e 's|^mount_program|#mount_program|g' -e 's|^mountopt|#mountopt|g' /etc/containers/storage.conf \
      && mkdir -p /var/lib/shared/vfs-images \
      && touch /var/lib/shared/vfs-images/images.lock \
      && mkdir -p /var/lib/shared/vfs-layers \
      && touch /var/lib/shared/vfs-layers/layers.lock \
      && curl -sSO https://raw.githubusercontent.com/whs-dot-hk/kubernetes-buildah-test/master/test.sh \
      && chmod a+x test.sh \
      && buildah unshare ./test.sh
